config/routes.rb
Rails.application.routes.draw do
  # get 'florists/:id' => 'florists#show'
  get 'plans/index'
  
  devise_for :florists, controllers: {
    sessions:      'florists/sessions',
    passwords:     'florists/passwords',
    registrations: 'florists/registrations',
    show:          'florists/show'
  }
  resources :florists, only: [:edit,:show]
  resources :florist do
    resources :shop_addresses
    resources :bouquets
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'flaanis#index'
  resources :flaanis
  resources :shop_address
  resources :dear_persons do
    resources :plans
    resources :favorites, only: [:new,:edit,:create]
  end
end

app/models/dear_person.rb
class DearPerson < ApplicationRecord
  belongs_to :user  # usersテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける
  has_one :favorite
  has_one :plan, dependent: :destroy
  has_one :address, dependent: :destroy
  # 空だと登録できないバリデーション
  with_options presence: true do
    validates :nick_name
    validates :image
    validates :birthday
    validates :anniversary
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }

  end
end

app/controllers/dear_persons_controller.rb
class DearPersonsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @dear_persons = DearPerson.all
    @user = User.find(current_user[:id])
    @plans = Plan.all
  end
  
  def new
    @dear_person = DearPerson.new
  end
  
  def create
    @dear_person = DearPerson.new(dear_person_params)
    if @dear_person.valid?
      
      @dear_person.save # バリデーションをクリアした時
      redirect_to  dear_person_path(@dear_person)
    else
      render 'new' # バリデーションに弾かれた時
    end
  end
  
  def show
    @dear_person = DearPerson.find(params[:id])
    @person_plan = nil
    @plans = Plan.all
    @plans.each do |plan|
      break @person_plan = plan if plan.dear_person_id == @dear_person.id
    end
    @favorite = nil
    @favorites = Favorite.all
      @favorites.each do |favorite|
        break @favorite = favorite if favorite.dear_person_id == @dear_person.id
      end
  end
  
  def edit
    @dear_person = DearPerson.find(params[:id])
  end

  def update
    @dear_person = DearPerson.find(params[:id])
    if @dear_person.update(dear_person_params)
      redirect_to root_path
    else
      render 'edit' # バリデーションに弾かれた時
    end
  end

  def destroy
    dear_person = DearPerson.find(params[:id])
    dear_person.destroy
    redirect_to root_path
  end

  private

  def dear_person_params
    params.require(:dear_person).permit(:image, :nick_name, :family_name, :last_name, :family_name_kana, :last_name_kana, :birthday, :anniversary).merge(user_id: current_user.id)
  end
end

app/helpers/dear_persons_helper.rb
module DearPersonsHelper
end

app/views/dear_persons/edit.html.erb
dear_person#new
<%= form_with model:@dear_person,  local: true do |form| %>
  <%# フォームの内部 %>
   <%# 出品画像 %>
    <div class="">
      <div class="">
        大切な人の写真
        <span class="">必須</span>
      </div>
      <div class="">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= form.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
  <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="">
      名前を入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :nick_name, placeholder: "ニックネーム" %>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="">
      名字を入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :family_name, placeholder: "例)田中" %>
    <%= form.text_field :last_name, placeholder: "例)ハナコ" %>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="">
      名字のカナ入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :family_name_kana, placeholder: "例)タナカ" %>
    <%= form.text_field :last_name_kana, placeholder: "例)ハナコ" %>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
   <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
        form.date_select(
          :birthday,
          class:'select-birth',
          id:"birth-date",
          use_month_numbers: true,
          prompt:'--',
          start_year: 1930,
          end_year: (Time.now.year - 5),
          date_separator: '%s'),
        "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
   <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">記念日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
        form.date_select(
          :anniversary,
          class:'select-birth',
          id:"birth-date",
          use_month_numbers: true,
          prompt:'--',
          :discard_year => true,
          date_separator: '%s'),
        "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <%# １つのフォーム終わり %>
  <div class=''>
    <%= form.submit "登録" ,class:"" %>
  </div>
<% end %>

app/views/dear_persons/index.html.erb
 <%= render "shared/second.header"%>
 <div class="main-contents"><%#大括り%>
    <div class="person-links"><%#リンク部分の括り%>
      <div class="link-box"><%= link_to "大切な人を登録する",  new_dear_person_path ,class:'person-edit-link'%></div>
      <div class="link-box"><%= link_to "マイページを編集する", edit_user_registration_path,class:'person-edit-link'%></div>
    </div>

   <div class="person-contents">
     <ul class='person-lists'>
       <li class='person-list'>
          <% @dear_persons.each do |person| %>
            <% if person.user_id == @user.id %>
               <div class="person-box">
                    <%= link_to image_tag( person.image,size: '250x300'),dear_person_path(person.id), class:'.dear-person-image'%>
                  <div class="person-list-parameters">
                    <%= person.nick_name%>
                  </div>
              </div>
            <% else %>
            <% end %>
          <%end%><%# personのeach%>
       </li>
     </ul>
    </div>
 </div>
  <%= render "shared/second.footer" %>

app/views/dear_persons/new.html.erb
<%= render "shared/second.header"%>
<div class="plans-field-new">
  <div class="login-forms">
    <h3 class="info-input-haedline">大切な人を登録</h3>
      <%= form_with model:@dear_person, url: dear_persons_path, local: true do |form| %>
      <%# フォームの内部 %>
       <%= render 'shared/error_messages', model: @dear_person %>
      <%# 画像登録 %>
      <div class="one-input-parts">
        <div class="field">
        大切な人の写真
        <span class="">必須</span>
        </div>
      <div class="">
        <div class="text">
          クリックしてファイルをアップロード
        </div>
        <%= form.file_field :image, id:"item-image" %>
      </div>
  </div>
    <%# /画像 %>
  <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :nick_name %>
      ニックネームを入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :nick_name, placeholder: "ニックネーム" %>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="form-text">
      名前を入力してください
      <span class="indispensable">必須</span>
    </div> 
    <div class="input-expiration-date-wrap">
    <%= form.text_field :family_name,class:"input-expiration-date dear-person-sizebox", placeholder: "例)田中" %>
    <%= form.text_field :last_name,class:"input-expiration-date dear-person-sizebox", placeholder: "例)花子" %>
    </div>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="form-text">
      名字のカナ入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :family_name_kana,class:"input-expiration-date", placeholder: "例)タナカ" %>
    <%= form.text_field :last_name_kana,class:"input-expiration-date", placeholder: "例)ハナコ" %>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
   <div class="one-input-parts">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
        form.date_select(
          :birthday,
          class:'select-birth',
          id:"birth-date",
          use_month_numbers: true,
          prompt:'--',
          start_year: 1930,
          end_year: (Time.now.year - 5),
          date_separator: '%s'),
        "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class='info-text text'>※ 本人情報は正しく入力してください。<br>会員登録後、修正するにはお時間を頂く場合があります。</div>
  </div>
  <%# １つのフォーム終わり %>

  <%# １つのフォーム始まり %>
   <div class="one-input-parts">
    <div class='form-text-wrap'>
      <label class="form-text">記念日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
        form.date_select(
          :anniversary,
          class:'select-birth',
          id:"birth-date",
          use_month_numbers: true,
          prompt:'--',
          :discard_year => true,
          date_separator: '%s'),
        "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class='info-text text'>※ 本人情報は正しく入力してください。<br>会員登録後、修正するにはお時間を頂く場合があります。</div>
  </div>
  <%# １つのフォーム終わり %>
  <div class=''>
    <%= form.submit "登録" ,class:"btn" %>
  </div>
  <% end %>
  </div>
</div>
<%= render "shared/second.footer"%>

app/views/dear_persons/show.html.erb
 <%= render "shared/second.header"%>
 <div class="show-contents">
    <div class="show-image-box">
      <%= image_tag @dear_person.image ,size:'350x350',class:"" %>
    </div>
    <div class="show-parameters-box">

      <div class="parameter-box">
        <div class="parameter-title">名前</div>
        <div class="show-parameter">
        <%= @dear_person.nick_name %>
        </div>
      </div>

      <div class="parameter-box">
        <div class="parameter-title">名字</div>
        <div class="show-parameter">
        <%= @dear_person.family_name %>
        </div>
      </div>

      <div class="parameter-box">
        <div class="parameter-title">名前</div>
        <div class="show-parameter">
        <%= @dear_person.last_name %>
        </div>
      </div>

      <div class="parameter-box">
        <div class="parameter-title">誕生日</div>
        <div class="show-parameter">
        <%= "#{@dear_person.birthday.month}月#{@dear_person.birthday.day}日" %>
        </div>
      </div>

      <div class="parameter-box">
        <div class="parameter-title">記念日</div>
        <div class="show-parameter">
        <%= "#{@dear_person.anniversary.month}月#{@dear_person.anniversary.day}日" %>
        </div>
      </div>
      
      <div class="parameter-box">
        <div class="parameter-title">プラン</div>
        <div class="show-parameter">

        <% if @plans.blank? %><%#すべてのプランが空だったとき%>
          <%= link_to 'プランを決める', dear_person_plans_path(@dear_person.id), method: :get, class:''%>
        <% elsif @person_plan == nil %>
          <%= link_to 'プランを決める', dear_person_plans_path(@dear_person.id), method: :get, class:''%>
        <% else %>
        <%= @person_plan.style%>
        <% end %>

        </div>
      </div>

      <div class="parameter-box">
        <div class="parameter-title">担当フローリスト</div>
        <div class="show-parameter">

        <% if @favorite.blank? %><%#すべての favorite_floristが空だったとき%>
          <%= link_to '専属のフローリストを決める',new_dear_person_favorite_path(@dear_person.id), method: :get, class:''%>
        <% elsif @favorite == nil %>
          <%= link_to '専属のフローリストを決める',new_dear_person_favorite_path(@dear_person.id), method: :get, class:''%>
        <% else %>
        <%= @favorite.florist.name%>
        <% end %>

        </div>
      </div>


    </div>
      <div class="show-edit-box">
      <div class="edit-box">
          <%= link_to "情報を編集する", edit_dear_person_path(@dear_person.id), method: :get, class:''%>
      </div>
      <div class="edit-box">
          <%= link_to "削除する", dear_person_path(@dear_person.id), method: :delete, class:'' %>
      </div>
      </div>
 </div>
  <%= render "shared/second.footer" %>