config/routes.rb
Rails.application.routes.draw do
  # get 'florists/:id' => 'florists#show'
  get 'plans/index'
  
  devise_for :florists, controllers: {
    sessions:      'florists/sessions',
    passwords:     'florists/passwords',
    registrations: 'florists/registrations',
    show:          'florists/show'
  }
  resources :florists, only: [:edit,:show]
  resources :florist do
    resources :shop_addresses
    resources :bouquets
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'flaanis#index'
  resources :flaanis
  resources :shop_address
  resources :dear_persons do
    resources :plans
    resources :favorites, only: [:new,:edit,:create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  # アクティブハッシュを使用する際のアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_time

  belongs_to :dear_person
  belongs_to :plan, optional: true
  belongs_to :address, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bouquet.rb
class Bouquet < ApplicationRecord
  belongs_to :florist  # usersテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける

  with_options presence: true do
    validates :style
    validates :commentary
    validates :image
  end
end

app/models/dear_person.rb
class DearPerson < ApplicationRecord
  belongs_to :user  # usersテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける
  has_one :favorite
  has_one :plan, dependent: :destroy
  has_one :address, dependent: :destroy
  # 空だと登録できないバリデーション
  with_options presence: true do
    validates :nick_name
    validates :image
    validates :birthday
    validates :anniversary
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }

  end
end

app/models/delivery_time.rb
class DeliveryTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '午前中（8時～12時' },
    { id: 3, name: '14時～16時' },
    { id: 4, name: '16時～18時' },
    { id: 5, name: '18時～20時' },
    { id: 6, name: '19時～21時' }
  ]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :florist
  belongs_to :dear_person
end

app/models/florist.rb
class Florist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bouquets
  has_many :favorite
  has_one_attached :avatar
  has_one :shop_address,  dependent: :destroy

  validates :avatar, presence: true
  validates :name, presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :plan, optional: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :dear_person
  has_one :address
  has_one :payment
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' }, { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' }, { id: 7, name: '福島県' }, { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' }, { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' }, { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' }, { id: 16, name: '富山県' }, { id: 17, name: '石川県' },
    { id: 18, name: '福井県' }, { id: 19, name: '山梨県' }, { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' }, { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' }, { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' }, { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' }, { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' }, { id: 34, name: '広島県' }, { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' }, { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' }, { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' }, { id: 43, name: '熊本県' }, { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]
end

app/models/shop_address.rb
class ShopAddress < ApplicationRecord
  # アクティブハッシュを使用する際のアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  belongs_to :florist  # floristテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける

  with_options presence: true do
    # 「住所」の郵便番号に関するバリデーション
    validates :shop_name
    validates :email
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Include hyphen(-)' }
    validates :city
    validates :house_number
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'is enter the phone number in 10 or 11 digits, half-width numbers.' }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #
         validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/shop_addresses_controller.rb
class ShopAddressesController < ApplicationController
  def new
    @shop_address = ShopAddress.new
  end

  def create
    @shop_address = ShopAddress.new(shop_address_params)
    if @shop_address.valid?
       @shop_address.save
       redirect_to  florist_path(@shop_address)
    else
        render 'new'
    end
  end

  def edit
    @shop_address = ShopAddress.find(current_florist[:id])
  end

  def update
    @shop_address = ShopAddress.find(current_florist[:id])
      if @shop_address.update(shop_address_params)
        redirect_to root_path
      else
        render 'edit' # バリデーションに弾かれた時
    end
  
  end

  def show
    @shop_address = ShopAddress.find(params[:shop_address_id])
  end

  private

  def shop_address_params
    params.require(:shop_address).permit(:image, :shop_name, :email, :postal_code,:prefecture_id , :city, :house_number,:building_name, :phone_number).merge(florist_id: current_florist.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bouquets_helper.rb
module BouquetsHelper
end

app/helpers/dear_persons_helper.rb
module DearPersonsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flaanis_helper.rb
module FlaanisHelper
end

app/helpers/florists_helper.rb
module FloristsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/shop_addresses_helper.rb
module ShopAddressesHelper
end

app/views/shop_addresses/edit.html.erb
<%= render "shared/second.header"%>
<div class="plans-field-new">
  <div class="login-forms">
    <h3 class="info-input-haedline">店舗情報を登録</h3>
      <%= form_with model:@shop_address, url: florists_shop_addresses_path, local: true do |form| %>
      <div class=''>
         <%= render 'shared/error_messages', model: @shop_address %>
      <%# 画像登録 %>
      <div class="one-input-parts">
        <div class="field">
        大切な人の写真
        <span class="">必須</span>
        </div>
      <div class="">
        <div class="text">
          クリックしてファイルをアップロード
        </div>
        <%= form.file_field :image, id:"item-image" %>
      </div>
  </div>
    <%# /画像 %>
 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :shop_name %>
      店舗名を入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :shop_name, placeholder: "店舗名" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :email %>
      E-mailを入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.email_field :email, placeholder: "flower@coom" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :postal_code %>
      郵便番号(-含む)
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :postal_code, placeholder: "123-4567" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
 <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: '----' }, {class:"select-box", id:"item-prefecture"}) %>
      </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :city %>
    市区町村
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :city, placeholder: "例）横浜市緑区" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :house_number %>
    番地
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :house_number, placeholder: "例）青山1-1" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :building_name %>
    ビル・建物名
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :building_name, placeholder: "例）柳ビル" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :phone_number %>
    電話番号
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :phone_number, placeholder: "例）09012345678" %>
  </div>
  <%# １つのフォーム終わり %>
  
    <%= form.submit "登録" ,class:"btn" %>
  </div>
  <% end %>
  </div>
</div>
<%= render "shared/second.footer"%>

app/views/shop_addresses/new.html.erb
<%= render "shared/second.header"%>
<div class="plans-field-new">
  <div class="login-forms">
    <h3 class="info-input-haedline">店舗情報を登録</h3>
      <%= form_with model:@shop_address, url: florist_shop_addresses_path, local: true do |form| %>
      <div class=''>
         <%= render 'shared/error_messages', model: @shop_address %>
      <%# 画像登録 %>
      <div class="one-input-parts">
        <div class="field">
        大切な人の写真
        <span class="">必須</span>
        </div>
      <div class="">
        <div class="text">
          クリックしてファイルをアップロード
        </div>
        <%= form.file_field :image, id:"item-image" %>
      </div>
  </div>
    <%# /画像 %>
 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :shop_name %>
      店舗名を入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :shop_name, placeholder: "店舗名" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :email %>
      E-mailを入力してください
      <span class="indispensable">必須</span>
    </div> 
    <%= form.email_field :email, placeholder: "flower@coom" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :postal_code %>
      郵便番号(-含む)
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :postal_code, placeholder: "123-4567" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
 <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: '----' }, {class:"select-box", id:"item-prefecture"}) %>
      </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :city %>
    市区町村
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :city, placeholder: "例）横浜市緑区" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :house_number %>
    番地
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :house_number, placeholder: "例）青山1-1" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :building_name %>
    ビル・建物名
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :building_name, placeholder: "例）柳ビル" %>
  </div>
  <%# １つのフォーム終わり %>

 <%# １つのフォーム始まり %>
  <div class="one-input-parts">
    <div class="field">
     <% form.label :phone_number %>
    電話番号
      <span class="indispensable">必須</span>
    </div> 
    <%= form.text_field :phone_number, placeholder: "例）09012345678" %>
  </div>
  <%# １つのフォーム終わり %>
  
    <%= form.submit "登録" ,class:"btn" %>
  </div>
  <% end %>
  </div>
</div>
<%= render "shared/second.footer"%>