config/routes.rb
Rails.application.routes.draw do
  # get 'florists/:id' => 'florists#show'
  get 'plans/index'
  
  devise_for :florists, controllers: {
    sessions:      'florists/sessions',
    passwords:     'florists/passwords',
    registrations: 'florists/registrations',
    show:          'florists/show'
  }
  resources :florists, only: [:edit,:show]
  resources :florist do
    resources :shop_addresses
    resources :bouquets
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'flaanis#index'
  resources :flaanis
  resources :shop_address
  resources :dear_persons do
    resources :plans
    resources :favorites, only: [:new,:edit,:create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  # アクティブハッシュを使用する際のアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_time

  belongs_to :dear_person
  belongs_to :plan, optional: true
  belongs_to :address, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bouquet.rb
class Bouquet < ApplicationRecord
  belongs_to :florist  # usersテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける

  with_options presence: true do
    validates :style
    validates :commentary
    validates :image
  end
end

app/models/dear_person.rb
class DearPerson < ApplicationRecord
  belongs_to :user  # usersテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける
  has_one :favorite
  has_one :plan, dependent: :destroy
  has_one :address, dependent: :destroy
  # 空だと登録できないバリデーション
  with_options presence: true do
    validates :nick_name
    validates :image
    validates :birthday
    validates :anniversary
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }

  end
end

app/models/delivery_time.rb
class DeliveryTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '午前中（8時～12時' },
    { id: 3, name: '14時～16時' },
    { id: 4, name: '16時～18時' },
    { id: 5, name: '18時～20時' },
    { id: 6, name: '19時～21時' }
  ]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :florist
  belongs_to :dear_person
end

app/models/florist.rb
class Florist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bouquets
  has_many :favorite
  has_one_attached :avatar
  has_one :shop_address,  dependent: :destroy

  validates :avatar, presence: true
  validates :name, presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :plan, optional: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :dear_person
  has_one :address
  has_one :payment
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' }, { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' }, { id: 7, name: '福島県' }, { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' }, { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' }, { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' }, { id: 16, name: '富山県' }, { id: 17, name: '石川県' },
    { id: 18, name: '福井県' }, { id: 19, name: '山梨県' }, { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' }, { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' }, { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' }, { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' }, { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' }, { id: 34, name: '広島県' }, { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' }, { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' }, { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' }, { id: 43, name: '熊本県' }, { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]
end

app/models/shop_address.rb
class ShopAddress < ApplicationRecord
  # アクティブハッシュを使用する際のアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  belongs_to :florist  # floristテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける

  with_options presence: true do
    # 「住所」の郵便番号に関するバリデーション
    validates :shop_name
    validates :email
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Include hyphen(-)' }
    validates :city
    validates :house_number
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'is enter the phone number in 10 or 11 digits, half-width numbers.' }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #
         validates :name, presence: true, length: { maximum: 20 }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bouquets_helper.rb
module BouquetsHelper
end

app/helpers/dear_persons_helper.rb
module DearPersonsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flaanis_helper.rb
module FlaanisHelper
end

app/helpers/florists_helper.rb
module FloristsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

  <div class="footer-contents">
    <div class="footer-contents-container">
    </div>

    <div class="footer-contents-container">
      <ul>
        <li>企業情報</li>
        <li>Flaaniについて</li>
        <li>お問い合わせ</li>
        <% if  florist_signed_in?%>
          <li> <%= link_to "ログアウト", destroy_florist_session_path, method: :delete,class: 'link-font-color' %></li>
          <li><i class="fas fa-user"></i><%= link_to "#{current_florist.name}としてログインしています",   florist_path(current_florist[:id]), method: :get, class: "link-font-color" %></li>
        <% else %>
          <li> <%= link_to "加盟店としてログインする",  new_florist_session_path, method: :get,class: '' %></li>
          <li> <%= link_to "加盟店として登録する",  new_florist_registration_path, method: :get,class: '' %></li>
        <% end %>
      </ul>    
    </div>

    <div class="footer-contents-container">
    </div>
  </div>
  <div class="copyright-parts">
  <p class="copyright">
    Copyright Flaani 2020.
  </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header-lower-fixed">
        <div class="heading off" id='opp'>
            <%= link_to image_tag("logo.png", class:"header-logo"), root_path %>
            <nav class="global-nav">
              <ul>
               <% if  florist_signed_in?%>
                  <li> <%= link_to "ログアウト", destroy_florist_session_path, method: :delete,class: 'link-font-color' %></li>
                  <li><%= link_to "Florist:  #{current_florist.name}",   florist_path(current_florist[:id]), method: :get, class: "link-font-color" %></li>
                <% else %>
                  <li> <%= link_to "Floristでログイン",  new_florist_session_path, method: :get,class: '' %></li>
                  <li> <%= link_to "Floristで登録",  new_florist_registration_path, method: :get,class: '' %></li>
                <% end %>

                <% if user_signed_in? %><%#ログインしていたら表示される%>
                <span><li class=".nav-list">
                  <%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class: "nav-list" %>
                  <%= link_to current_user.name,dear_persons_path, method: :get, class: "nav-list" %>
                </li></span>
                <% else %><%#ログインしていなかったら以下が表示される%>
                <li class="menu-list">
                  <span class="material-icons">local_florist</span>
                    <%= link_to 'SIGN IN',new_user_session_path, method: :post, class: "nav-list" %>
                </li>
                <li class="menu-list">
                    <i class="fas fa-user nav-list"></i>
                    <%= link_to 'SIGN UP',new_user_registration_path, method: :get, class: "nav-list" %>
                </li>
                <% end %>
              </ul>
            </nav>
        </div>
</header>

app/views/shared/_second.footer.html.erb
<footer class="second-footer">
  <div class="footer-ligo-box">
      <%= link_to image_tag("logo.png", class:"footer-logo"), root_path %>
  </div>
</footer>

app/views/shared/_second.header.html.erb
<header class="second-header">
  <div class="second-heading">
      <%= link_to image_tag("logo.png", class:"header-logo"), root_path %>
  </div>
</header>