config/routes.rb
Rails.application.routes.draw do
  # get 'florists/:id' => 'florists#show'
  get 'plans/index'
  
  devise_for :florists, controllers: {
    sessions:      'florists/sessions',
    passwords:     'florists/passwords',
    registrations: 'florists/registrations',
    show:          'florists/show'
  }
  resources :florists, only: [:edit,:show]
  resources :florist do
    resources :shop_addresses
    resources :bouquets
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'flaanis#index'
  resources :flaanis
  resources :shop_address
  resources :dear_persons do
    resources :plans
    resources :favorites, only: [:new,:edit,:create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  # アクティブハッシュを使用する際のアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_time

  belongs_to :dear_person
  belongs_to :plan, optional: true
  belongs_to :address, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bouquet.rb
class Bouquet < ApplicationRecord
  belongs_to :florist  # usersテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける

  with_options presence: true do
    validates :style
    validates :commentary
    validates :image
  end
end

app/models/dear_person.rb
class DearPerson < ApplicationRecord
  belongs_to :user  # usersテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける
  has_one :favorite
  has_one :plan, dependent: :destroy
  has_one :address, dependent: :destroy
  # 空だと登録できないバリデーション
  with_options presence: true do
    validates :nick_name
    validates :image
    validates :birthday
    validates :anniversary
    validates :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }

  end
end

app/models/delivery_time.rb
class DeliveryTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '午前中（8時～12時' },
    { id: 3, name: '14時～16時' },
    { id: 4, name: '16時～18時' },
    { id: 5, name: '18時～20時' },
    { id: 6, name: '19時～21時' }
  ]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :florist
  belongs_to :dear_person
end

app/models/florist.rb
class Florist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bouquets
  has_many :favorite
  has_one_attached :avatar
  has_one :shop_address,  dependent: :destroy

  validates :avatar, presence: true
  validates :name, presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :plan, optional: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :dear_person
  has_one :address
  has_one :payment
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' }, { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' }, { id: 7, name: '福島県' }, { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' }, { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' }, { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' }, { id: 16, name: '富山県' }, { id: 17, name: '石川県' },
    { id: 18, name: '福井県' }, { id: 19, name: '山梨県' }, { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' }, { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' }, { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' }, { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' }, { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' }, { id: 34, name: '広島県' }, { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' }, { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' }, { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' }, { id: 43, name: '熊本県' }, { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]
end

app/models/shop_address.rb
class ShopAddress < ApplicationRecord
  # アクティブハッシュを使用する際のアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  belongs_to :florist  # floristテーブルとのアソシエーション
  has_one_attached :image # 各画像と1対1で結びつける

  with_options presence: true do
    # 「住所」の郵便番号に関するバリデーション
    validates :shop_name
    validates :email
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Include hyphen(-)' }
    validates :city
    validates :house_number
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'is enter the phone number in 10 or 11 digits, half-width numbers.' }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #
         validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/flaanis_controller.rb
class FlaanisController < ApplicationController
  def index
    @florists = Florist.all
    @bouquets = Bouquet.all
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :dear_person_set, only: [:index, :create]
  def index
    @plan = Plan.new
  end

  def create
    @plan = PlanAddress.new(plan_params)
    if @plan.valid?
      pay_item
      @plan.save # バリデーションをクリアした時
      NotificationMailer.send_confirm_to_user(@plan).deliver
      redirect_to root_path
    else
      render 'index' # バリデーションに弾かれた時
    end
  end

  def edit
  end

  private

  def plan_params
    params.permit(:dear_person_id, :token, :price, :style, :postal_code, :prefecture_id, :city, :house_number, :building_name, :phone_number, :delivery_time_id).merge(user_id: current_user.id).merge(dear_person_id: @dear_person.id)
  end

  def dear_person_set
    @dear_person = DearPerson.find(params[:dear_person_id])
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # PAY.JPテスト秘密鍵
    Payjp::Charge.create(
      amount: @plan.price, # 商品の値段
      card: params[:token], # カードトークン
      currency: 'jpy'                             # 通貨の種類(日本円)
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bouquets_helper.rb
module BouquetsHelper
end

app/helpers/dear_persons_helper.rb
module DearPersonsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flaanis_helper.rb
module FlaanisHelper
end

app/helpers/florists_helper.rb
module FloristsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/flaanis/index.html.erb
<%= render "shared/header.html.erb"%>
<%# トップコンテンツ %>
<div class="top-contents">
  <div class="top-contents-container">
    <h3 class='top-contents-title'>忘れても届く</h3>
    <p class='top-contents-text'>
    Flaaniは、毎日が忙しく大切な人の記念日を忘れがちな
    <br>あなたの代わりに、ブーケをお届けするサービスです。
    <br>是非、Flaaniを活用してみませんか。<br>
    </p>     
    <div class="start-btn-box">
    <%= link_to "大切な人を登録する",  new_dear_person_path ,class:'start-btn'%>
    </div>
    
  </div>  
</div>
<%# end トップコンテンツ %>

<%# トップミドル部分 %>
<div class="top-contents-images">
  <div class="top-content-container">
    <%= image_tag asset_path('main-image3.jpg') %>
    <div class="content-text-box">
    <h5>シンプルな登録</h5>
    <p>
      ステップは、簡単な登録・プランを選ぶ・決済の3つだけです。<br>
    </p>
    </div>
  </div>
  <div class="top-content-container">
    <%= image_tag asset_path('main-image1.png') %>
    <div class="content-text-box">
    <h5>経験豊富なフローリストが制作</h5>
    <p>
      大切な人に、満足して頂ける花束をお届けいたします。<br>
    </p>
    </div>
  </div>
  <div class="top-content-container">
    <%= image_tag asset_path('main-image2.jpg') %>
    <div class="content-text-box">
    <h5>毎年指定の場所へ</h5>
    <p>登録しておいた場所へ専用のメッセージカードを添えてお届けいたします。
    </p>
    </div>
  </div>
</div>
<%# endトップミドル部分 %>

<%# バックグラウンド部分 %>
<div class="background-space1">
</div>
<%# endバックグラウンド部分 %>

<%# スタイル紹介部分 %>
<div class="styles-contents">
  <div class="style-contents-inner">
    <div class="style-title">
      <h3 class="style-title">選択を簡単に</h3>
      <div class="style-Description">
        <p>Flaaniは4つのスタイルから選ぶだけでfloristが季節のお花を使って素敵なブーケを束ねてくれます。<br>
        プランはいつでも変更可能です。
        </p>
      </div>
    </div>
    <div class="style-container">
      <div class="bright-style"></div>
      <div class="cute-style"></div>
      <div class="cool-style"></div>
      <div class="natural-style"></div>
    </div>
  </div>
</div>
  
<%# バックグラウンド部分 %>
<div class="background-space2">
</div>
<%# endバックグラウンド部分 %>

<%# 登録フローリスト部分 %>
<div class="florist-contents">
 <h3 class='top-contents-title'>Florists</h3>
  <p>登録されたフローリスト達、あなたの大切な人の専属として登録できます。<br>プレゼントの制作をお気に入りのフローリストに任せてみてはいかがでしょうか
  </p>
  <div class="florist-list">
    <% @florists.each do |florist| %>
    <%= link_to florist_path(florist.id) do %>
    <div class="one-florist">
      <div class="florist-image">
        <%= image_tag florist.avatar , :size =>'240x320' %>
      </div>
      <div class="content-text-box2">
        <%= florist.name %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
<%# end登録フローリスト部分 %>

<%# バックグラウンド部分 %>
<div class="background-space3">
</div>
<%# endバックグラウンド部分 %>

<%# トップミドル部分 %>
<div class="flower-area">
 <h3 class='top-contents-title'>Bouquet</h3>
  <p>フローリストが制作したブーケです。<br>気に入ったブーケを制作したフローリストをチェックしましょう。
        </p>
  <div class="top-contents-images2">
  <% @bouquets.each do |bouquet| %>
   <%= link_to  florist_bouquet_path(bouquet.florist.id,bouquet.id ) do %>
   
    <div class="top-content-container2">
    <div class="top-content-image-box">
      <%= image_tag bouquet.image, :size =>'300x200' %>
    </div>
      <div class="content-text-box2">
      <h5>
       <%= bouquet.style %>
      </h5>
      <p>
       <%= bouquet.commentary %>
      </p>
    </div>
  </div>
      <% end %>
    <% end %>
<% if  @bouquets.nil? %>
  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img2.png') %>
      </div>
      <div class="content-text-box2">
        <h5>SIMPLE</h5>
        <p>
          スカビオサとオクラレルカ、千日紅をだけで束ねシンプルなブーケに仕上げました。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img3.png') %>
      </div>
      <div class="content-text-box2">
        <h5>BRIGHT</h5>
        <p>
          トーンを明るくガーベラのオレンジケーキ、ベビーロマンティカなど可愛いくコロンと仕上げてます。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img4.png') %>
      </div>
      <div class="content-text-box2">
        <h5>COOL</h5>
        <p>
          大輪のバラはフリーダムとアンティグアのカーネーションの組み合わせで大人っぽさを演出しました。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img5.png') %>
      </div>
      <div class="content-text-box2">
        <h5>SIMPLE</h5>
        <p>
          白いバラは「ホワイトマカロン」そして日持ちのする紫陽花「ミニグリーン」に葉物を添えてシンプルに仕上げました。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img6.png') %>
      </div>
        <div class="content-text-box2">
        <h5>NATURAL</h5>
        <p>
          ユーカリの「ポポラス」、「アンティーク紫陽花」。アクセントにプロテアを使いスワッグを意識したブーケです
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img7.png') %>
      </div>
        <div class="content-text-box2">
        <h5>COOL</h5>
        <p>
          ダリアのムーンストーンをメインに大人らしさを感じるブーケに仕上げました。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img8.png') %>
      </div>
      <div class="content-text-box2">
        <h5>CUUTE</h5>
        <p>
          ピンクを抑えめにして全体的に明るく仕上げたブーケ。メインはピタハヤという薔薇。おすすめです
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img9.png') %>
      </div>
      <div class="content-text-box2">
        <h5>SIMPLE</h5>
        <p>
        かすみ草だけを活かしたブーケ。ただシンプルに。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img10.png') %>
      </div>
      <div class="content-text-box2">
        <h5>NATURAL</h5>
        <p>
          完全なNATURALというより少し華やかさをプラスしたブーケです。スカビオサ、トルコキキョウなどをメインに。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
      <%= image_tag asset_path('flower-img11.png') %>
      </div>
      <div class="content-text-box2">
        <h5>COOL</h5>
        <p>
        ユリ(ソルボンヌ)をフォーカルにかっこよく仕上げました。
      </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img12.png') %>
      </div>
      <div class="content-text-box2">
        <h5>SIMPLE</h5>
        <p>
          かすみ草をメインに丸く作りつつ、ラッピングで大人っぽさを演出しています。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img13.png') %>
      </div>
      <div class="content-text-box2">
        <h5>CUTE</h5>
        <p>
          ダリア、アイスティーなど。Brightに近づけながらもラッピングでCUTEさを演出しています
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img14.png') %>
      </div>
      <div class="content-text-box2">
        <h5>SIMPLE</h5>
        <p>
          スイートピーのウルトラヴァイオレットと季節のグリーンとのシンプルなブーケ。
        </p>
      </div>
    </div>
  </div>

  <div class="top-contents-images2">
    <div class="top-content-container2">
      <div class="top-content-image-box">
        <%= image_tag asset_path('flower-img15.png') %>
      </div>
      <div class="content-text-box2">
        <h5>NATURAL</h5>
        <p>
          ナルコラン・アスパラガス観賞用・ハーブなど多種のグリーンを使用しました。
        </p>
      </div>
    </div>
  </div>

</div><%#flower部分の大枠%>
<% end %>
<%= render "shared/footer.html.erb"%>